// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUKhgdzorUq92v-pECw6am-W7110lZjA',
    appId: '1:390628209295:web:3b69cf913585dbdda9b6fa',
    messagingSenderId: '390628209295',
    projectId: 'app-auth-bc25f',
    authDomain: 'app-auth-bc25f.firebaseapp.com',
    storageBucket: 'app-auth-bc25f.firebasestorage.app',
    measurementId: 'G-GGF69JFM1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALSz1aflNfa4ZZbUClusxmoKremKeT2l8',
    appId: '1:390628209295:android:ab9cefc3f85e10f5a9b6fa',
    messagingSenderId: '390628209295',
    projectId: 'app-auth-bc25f',
    storageBucket: 'app-auth-bc25f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7QPZ-j-mEhuFfsqk7L9kqtgxH5yWU8S4',
    appId: '1:390628209295:ios:5747b4d3a5620982a9b6fa',
    messagingSenderId: '390628209295',
    projectId: 'app-auth-bc25f',
    storageBucket: 'app-auth-bc25f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7QPZ-j-mEhuFfsqk7L9kqtgxH5yWU8S4',
    appId: '1:390628209295:ios:5747b4d3a5620982a9b6fa',
    messagingSenderId: '390628209295',
    projectId: 'app-auth-bc25f',
    storageBucket: 'app-auth-bc25f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUKhgdzorUq92v-pECw6am-W7110lZjA',
    appId: '1:390628209295:web:503cf6228c685b56a9b6fa',
    messagingSenderId: '390628209295',
    projectId: 'app-auth-bc25f',
    authDomain: 'app-auth-bc25f.firebaseapp.com',
    storageBucket: 'app-auth-bc25f.firebasestorage.app',
    measurementId: 'G-3VJ2SL6GTR',
  );
}
